case_10 were not generated and case_9 has error with "all_data.json" because I interrupted the simulation while running
Therefore, I continued without case_9, case_10


